# Welcome to Jekyll!
#

# Site settings
title: Fahrservice Paeschke
description: |
  Ihr Fahrservice mit Herz im Uckerland.
  Fahrten zum Arzt, ins Krankenhaus oder zum Einkauf.
  Wir sind f√ºr Sie da.
owner: Michael Paeschke # or company name
first_published: 2018
email: info@fahrservice-paeschke.de
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://neoklosch.github.io/fahrservice-paeschke" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

theme: jekyll-theme-slate
